### PR TITLE
Redesign Clan Page

### PR DESCRIPTION
**Pull request by INTJT**

### CODE REVIEW

**Comment by INTJT** [comment]
[Clan page | Title to Clan table](https://trello.com/c/rdANXyzs/216-clan-page-title-to-clan-table)

**Comment by INTJT** [comment]
[Clan page | Title to Clan table](https://trello.com/c/rdANXyzs/216-clan-page-title-to-clan-table)

**Comment by INTJT** [comment]
[[Clan page] Align elements on page](https://trello.com/c/YyoAgFNH/219-clan-page-align-elements-on-page)

**Comment by INTJT** [comment]
[Clan page | design Delete modal window](https://trello.com/c/Jq5NwtEC/218-clan-page-design-delete-modal-window)

**Comment by INTJT** [comment]
[[Clan page] If user is not in THIS clan he can see 'Invite' button](https://trello.com/c/vdYg5xCX/270-clan-page-if-user-is-not-in-this-clan-he-can-see-invite-button)

**Comment by INTJT** [comment]
[Clan page | connect with server | clan avatar and cover](https://trello.com/c/bP3ZV9wp/215-clan-page-connect-with-server-clan-avatar-and-cover)

**Comment by INTJT** [comment]
[[Clans page] Align elements in the table, button size](https://trello.com/c/jVetYoEv/234-clans-page-align-elements-in-the-table-button-size)

**Comment by INTJT** [comment]
[[Clans page] Align elements in the table, button size](https://trello.com/c/jVetYoEv/234-clans-page-align-elements-in-the-table-button-size)

**Review by Paul-Vasylenko — APPROVED** [review]
amazing job man

**Pull request merged**
