### PR TITLE
 Added component Header, Avatar and Label (for rank and mark)

### PR DESCRIPTION
**Pull request by AlexanderKhapchenko**

### CODE REVIEW

**Comment by AlexanderKhapchenko** [comment]
[Header Layout](https://trello.com/c/HqhM2hNw/12-header-layout)

**Comment by AlexanderKhapchenko** [comment]
[Header Layout](https://trello.com/c/HqhM2hNw/12-header-layout)

**Comment by AlexanderKhapchenko** [comment]
[Header Layout](https://trello.com/c/HqhM2hNw/12-header-layout)

**Review by kyrylo-burmelov — CHANGES_REQUESTED** [review]
- You need to add container for header. Add mocked data (you can use data from design but without user image)
- Review how you are using line-height property. For most of the cases you do not need to use it. Read [best practices](https://medium.com/@lampewebdevelopment/how-css-line-height-works-and-best-practices-4b0aefa4f4c4).
- You need to avoid height jumping when hovering this menu
image
- See comments below

**Review by kyrylo-burmelov — APPROVED** [review]

**Pull request merged**
