### PR TITLE
Fix styles and validation for SignIn/SignUp

### PR DESCRIPTION
**Pull request by svitlua**

### CODE REVIEW

**Comment by svitlua** [comment]
[Sign-in/sign-up notifications](https://trello.com/c/xusLg7a2/44-sign-in-sign-up-notifications)

**Comment by svitlua** [comment]
[Sign-in/sign-up notifications](https://trello.com/c/xusLg7a2/44-sign-in-sign-up-notifications)

**Comment by svitlua** [comment]
[[Sign up page] UI design does not meet mockup](https://trello.com/c/HrcETBTx/45-sign-up-page-ui-design-does-not-meet-mockup)

**Comment by svitlua** [comment]
[[Sign-In page] Password with one sign on the Sign-in page is valid](https://trello.com/c/U7EKau7D/46-sign-in-page-password-with-one-sign-on-the-sign-in-page-is-valid)

**Review by Paul-Vasylenko — APPROVED** [review]

**Pull request merged**
